
# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
version = "0.0.1"
name = "Sample Java Maven Buildpack"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
